name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Create secrets
      uses: 1arp/create-a-file-action@0.2
      with:
       # Path from cwd where file is to be created
        path: /
        file: secrets.h
        content: |
          #pragma once
          #define WIFI_SSID "*"
          ##define WIFI_PASSWORD "*"
    - name: Run PlatformIO
      run: pio run -e HARDAWARE_TYPE_TMATCH_WITH_RELAYS -e HARDAWARE_TYPE_TMATCH_WITH_STEPPERS -e HARDAWARE_TYPE_LMATCH_WITH_STEPPERS
